- datasource: s3,file
  bucketname:
  prefixkey:
  path:
- filereader:
    linetokenizer: "1,3,4"
    delimiter: "|"
    skiplines: 0
    lastrecordprefix: "employee4"
    rowmappermodel: RowMapModel
    comitsize: 10000